export default [
  {
    id: 1,
    firstName: "علی",
    lastName: "احمدی",
    age: 18,
    height: 183,
    birthdate: "",
    location: "tehran",
  },
  {
    id: 2,
    firstName: "علی رضا",
    lastName: "احمدی",
    age: 18,
    height: 183,
    birthdate: "",
    location: "tehran",
  },
  {
    id: 3,
    firstName: "نیما",
    lastName: "احمدی",
    age: 18,
    height: 183,
    birthdate: "",
    location: "tehran",
  },
  {
    id: 4,
    firstName: "علی",
    lastName: "احمدی",
    age: 18,
    height: 183,
    birthdate: "",
    location: "tehran",
  },
  {
    id: 5,
    firstName: "علی",
    lastName: "احمدی",
    age: 18,
    height: 183,
    birthdate: "",
    location: "tehran",
  },
];
